config/routes.rb
Rails.application.routes.draw do
  
  
  
  resources :lens
  resources :sunglasses
  resources :frames
  resources :products
  resources :employees
  resources :stores
  resources :roles
  get 'home/index'
  devise_for :users

  root "home#index"

  get  'member/index'
  get  'member/create'
  post 'member/create_user'

  get 'inventory/index'
  get 'inventory/barcode_generate'
  post 'inventory/generate_barcode'
  get 'inventory/get_frame_data'

  get 'customer/index'
  get 'customer/create'
  get 'customer/edit'
  post 'customer/create_customer'

  get 'invoices/get_cust_data'
  get 'invoices/get_item_product'
  get 'invoices/edit'
  post 'invoices/generate_cust_invoice'

  get 'report/show_order_data'
  get 'report/index'
  get 'report/csv'
  get 'report/excel'

  get 'invoices/get_orderitemdata'


  resources :orders

  resources :invoices, except: [:destroy] do
    collection do
      match 'search' => 'invoices#search', via: [:get, :post], as: :search
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/frame.rb
class Frame < ApplicationRecord
  belongs_to :store
  belongs_to :product
  has_many :inventory_items
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
	belongs_to :frame, optional: true
	belongs_to :len, optional: true
	belongs_to :sunglasse, optional: true
	belongs_to :store
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  def self.delete_old
  	@old_invoices = Invoice.where('date < ?', 30.days.ago)
  	@old_invoices.delete_all
  end
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/len.rb
class Len < ApplicationRecord
  belongs_to :store
  belongs_to :product
  has_many :inventory_items
end

app/models/order.rb
require 'csv'

class Order < ApplicationRecord
	belongs_to :store
  has_many :order_details

	def self.to_csv
    attributes = %w{id store total_amt delivery_date }

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |order|
        csv << attributes.map{ |attr| order.send(attr) }
      end
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/store.rb
class Store < ApplicationRecord
	has_many :users
end

app/models/sunglasse.rb
class Sunglasse < ApplicationRecord
	belongs_to :store
	belongs_to :product
  	has_many :inventory_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  belongs_to :store
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @lastId = Employee.maximum(:id)
    if @lastId.present?
       @lastId = @lastId + 1
    else
      @lastId = 1
    end
  end

  # GET /employees/1/edit
  def edit
    @lastId = @employee.emp_id
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to({:action => :index}, {:notice => 'Employee was successfully created.'}) }
        # format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to({:action => :index}, {:notice => 'Employee was successfully updated.'}) }
        # format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:emp_id, :name, :mobile, :email, :optometrist, :hto, :manager, :active)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lens_helper.rb
module LensHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="box-body">
    <div class="form-group">

    <%= form.label :emp_id %>
    <%= form.text_field :emp_id, class: "form-control" , :value => @lastId %>

    <%= form.label :name %>
    <%= form.text_field :name , class: "form-control"%>

    <%= form.label :mobile %>
    <%= form.text_field :mobile , class: "form-control"%>

    <%= form.label :email %>
    <%= form.text_field :email , class: "form-control" %>

    <%= form.label :optometrist %>
    <%= form.check_box :optometrist , class: "form-check"%>

    <%= form.label :hto %>
    <%= form.check_box :hto , class: "form-check"%>

    <%= form.label :manager %>
    <%= form.check_box :manager , class: "form-check"%>

    <%= form.label :active %>
    <%= form.check_box :active , class: "form-check"%>

  <div class="box-footer">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
</div>
</div>

app/views/employees/edit.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
       <!--  <h1>
          Dashboard
          <small>Control panel</small>
        </h1> -->
        <ol class="breadcrumb">
          <li class="active">
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
            </li>
          </ol>
        </section>
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-8">
              <!-- general form elements -->
              <div class="box box-header">
                <div class="box-header with-border">
                <h3 class="box-title">Edit Employee</h3>
                </div>

                <%= render 'form', employee: @employee %>

                <%#= link_to 'Show', @role %> 
                <%#= link_to 'Back', roles_path %>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </body>

app/views/employees/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <!-- <h1>
          Dashboard
          <small>Control panel</small>
        </h1> -->
        <ol class="breadcrumb">
          <li class="active">
            <!-- <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a> -->
            </li>
          </ol>
        </section>
        <section class="content">
          <div class="col-md-12">
            <div class="box">
              <div class="box-header with-border">
                <h3 class="box-title">Total Employees (<%= @employees.count %>)</h3>
                <%= link_to 'New Employee', new_employee_path , { class: "btn btn-primary newAddBtn"}%>
              </div>
              <!-- /.box-header -->
              <div class="box-body">
                <table class="table table-bordered table-hover">
                  <tr>
                     <th>Emp</th>
                     <th>Name</th>
                     <th>Mobile</th>
                     <th>Email</th>
                     <th>Optometrist</th>
                     <th>Hto</th>
                     <th>Manager</th>
                     <th>Active</th>
                    
                    <th>
                      <i class="ion ion-edit"></i>
                    </th>
                    <th>
                      <i class="ion ion-trash-b"></i>
                    </th>
                  </tr>
                  <% @employees.each do |employee| %>
                  <tr>
                    <td><%= employee.emp_id %></td>
                    <td><%= employee.name %></td>
                    <td><%= employee.mobile %></td>
                    <td><%= employee.email %></td>
                    <td><%= employee.optometrist %></td>
                    <td><%= employee.hto %></td>
                    <td><%= employee.manager %></td>
                    <td><%= employee.active %></td>
                    <td><%= link_to "", edit_employee_path(employee), { class: "ion ion-edit"} %></td>
                    <td>
                      <%= link_to employee, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="ion ion-trash-b"></i>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                </table>
              </div>
            </div>
            <!-- /.box -->
          </div>
          <br>
        </section>
      </div>
    </div>
  </body>

app/views/employees/new.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <!-- <h1>
          Dashboard
          <small>Control panel</small>
        </h1> -->
        <ol class="breadcrumb">
          <li class="active">
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
            </li>
          </ol>
        </section>
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-header">
                <div class="box-header with-border">
                  <h3 class="box-title">New Store</h3>
                </div>

              <%= render 'form', employee: @employee %>

                <%#= link_to 'Back', roles_path %>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </body>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emp:</strong>
  <%= @employee.emp_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @employee.mobile %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Optometrist:</strong>
  <%= @employee.optometrist %>
</p>

<p>
  <strong>Hto:</strong>
  <%= @employee.hto %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @employee.manager %>
</p>

<p>
  <strong>Active:</strong>
  <%= @employee.active %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>