config/routes.rb
Rails.application.routes.draw do
  
  
  
  resources :lens
  resources :sunglasses
  resources :frames
  resources :products
  resources :employees
  resources :stores
  resources :roles
  get 'home/index'
  devise_for :users

  root "home#index"

  get  'member/index'
  get  'member/create'
  post 'member/create_user'

  get 'inventory/index'
  get 'inventory/barcode_generate'
  post 'inventory/generate_barcode'
  get 'inventory/get_frame_data'

  get 'customer/index'
  get 'customer/create'
  get 'customer/edit'
  post 'customer/create_customer'

  get 'invoices/get_cust_data'
  get 'invoices/get_item_product'
  get 'invoices/edit'
  post 'invoices/generate_cust_invoice'

  get 'report/show_order_data'
  get 'report/index'
  get 'report/csv'
  get 'report/excel'

  get 'invoices/get_orderitemdata'


  resources :orders

  resources :invoices, except: [:destroy] do
    collection do
      match 'search' => 'invoices#search', via: [:get, :post], as: :search
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/frame.rb
class Frame < ApplicationRecord
  belongs_to :store
  belongs_to :product
  has_many :inventory_items
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
	belongs_to :frame, optional: true
	belongs_to :len, optional: true
	belongs_to :sunglasse, optional: true
	belongs_to :store
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  def self.delete_old
  	@old_invoices = Invoice.where('date < ?', 30.days.ago)
  	@old_invoices.delete_all
  end
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/len.rb
class Len < ApplicationRecord
  belongs_to :store
  belongs_to :product
  has_many :inventory_items
end

app/models/order.rb
require 'csv'

class Order < ApplicationRecord
	belongs_to :store
  has_many :order_details

	def self.to_csv
    attributes = %w{id store total_amt delivery_date }

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |order|
        csv << attributes.map{ |attr| order.send(attr) }
      end
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/store.rb
class Store < ApplicationRecord
	has_many :users
end

app/models/sunglasse.rb
class Sunglasse < ApplicationRecord
	belongs_to :store
	belongs_to :product
  	has_many :inventory_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  belongs_to :store
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to({:action => :index}, {:notice => 'Store was successfully created.'}) }
        # format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to({:action => :index}, {:notice => 'Store was successfully updated.'}) }
        # format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address, :phone)
    end
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lens_helper.rb
module LensHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="box-body">
    <div class="form-group">

    <%#= form.label :name %>
     <label>Name</label>
    <%= form.text_field :name , class: "form-control" , required: true%>

    <%#= form.label :address %>
     <label>Address</label>
    <%= form.text_area :address , class: "form-control" , rows: "3", required: true %>

    <%#= form.label :phone %>
     <label>Phone</label>
    <%= form.number_field :phone , class: "form-control" , required: true %>

  <div class="box-footer">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
</div>
</div>



                 
                  

app/views/stores/edit.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
       <!--  <h1>
          Dashboard
          <small>Control panel</small>
        </h1> -->
        <ol class="breadcrumb">
          <li class="active">
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
            </li>
          </ol>
        </section>
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-8">
              <!-- general form elements -->
              <div class="box box-header">
                <div class="box-header with-border">
                <h3 class="box-title">Edit Store</h3>
                </div>

                <%= render 'form', store: @store %>

                <%#= link_to 'Show', @role %> 
                <%#= link_to 'Back', roles_path %>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </body>

app/views/stores/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <!-- <h1>
          Dashboard
          <small>Control panel</small>
        </h1> -->
        <ol class="breadcrumb">
          <li class="active">
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
            </li>
          </ol>
        </section>
        <section class="content">
          <div class="col-md-8">
            <div class="box">
              <div class="box-header with-border">
                <h3 class="box-title">Stores (<%= @stores.count %>)</h3>
                <%= link_to 'New Store', new_store_path , { class: "btn btn-primary newAddBtn"}%>
              </div>
              <!-- /.box-header -->
              <div class="box-body">
                <table class="table table-bordered table-hover">
                  <tr>
                     <th>Name</th>
                     <th>Address</th>
                     <th>Phone</th>
                    
                    <th>
                      <i class="ion ion-edit"></i>
                    </th>
                    <th>
                      <i class="ion ion-trash-b"></i>
                    </th>
                  </tr>
                  <% @stores.each do |store| %>
                  <tr>
                      <td><%= store.name %></td>
                     <td><%= store.address %></td>
                     <td><%= store.phone %></td>

                    <td><%= link_to "", edit_store_path(store), { class: "ion ion-edit"} %></td>
                    <td>
                      <%= link_to store, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="ion ion-trash-b"></i>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                </table>
              </div>
            </div>
            <!-- /.box -->
          </div>
          <br>
        </section>
      </div>
    </div>
  </body>

app/views/stores/new.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <!-- <h1>
          Dashboard
          <small>Control panel</small>
        </h1> -->
        <ol class="breadcrumb">
          <li class="active">
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
            </li>
          </ol>
        </section>
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-header">
                <div class="box-header with-border">
                  <h3 class="box-title">New Store</h3>
                </div>

               <%= render 'form', store: @store %>

                <%#= link_to 'Back', roles_path %>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </body>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store.phone %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>