config/routes.rb
Rails.application.routes.draw do
  
  
  
  resources :lens
  resources :sunglasses
  resources :frames
  resources :products
  resources :employees
  resources :stores
  resources :roles
  get 'home/index'
  devise_for :users

  root "home#index"

  get  'member/index'
  get  'member/create'
  post 'member/create_user'

  get 'inventory/index'
  get 'inventory/barcode_generate'
  post 'inventory/generate_barcode'
  get 'inventory/get_frame_data'

  get 'customer/index'
  get 'customer/create'
  get 'customer/edit'
  post 'customer/create_customer'

  get 'invoices/get_cust_data'
  get 'invoices/get_item_product'
  get 'invoices/edit'
  post 'invoices/generate_cust_invoice'

  get 'report/show_order_data'
  get 'report/index'
  get 'report/csv'
  get 'report/excel'

  get 'invoices/get_orderitemdata'


  resources :orders

  resources :invoices, except: [:destroy] do
    collection do
      match 'search' => 'invoices#search', via: [:get, :post], as: :search
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/frame.rb
class Frame < ApplicationRecord
  belongs_to :store
  belongs_to :product
  has_many :inventory_items
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  def self.delete_old
  	@old_invoices = Invoice.where('date < ?', 30.days.ago)
  	@old_invoices.delete_all
  end
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/len.rb
class Len < ApplicationRecord
  belongs_to :store
  belongs_to :product
  has_many :inventory_items
end

app/models/order.rb
require 'csv'

class Order < ApplicationRecord
	belongs_to :store
  has_many :order_details

	def self.to_csv
    attributes = %w{id store total_amt delivery_date }

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |order|
        csv << attributes.map{ |attr| order.send(attr) }
      end
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/store.rb
class Store < ApplicationRecord
	has_many :users
end

app/models/sunglasse.rb
class Sunglasse < ApplicationRecord
	belongs_to :store
	belongs_to :product
  	has_many :inventory_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  belongs_to :store
end

app/controllers/inventory_controller.rb
require 'barby'
require 'barby/barcode/ean_13'
require 'barby/barcode/code_128'
# require 'barby/outputter/ascii_outputter'
require 'barby/outputter/html_outputter'
require 'chunky_png'
require 'barby/outputter/png_outputter'


class InventoryController < ApplicationController
  def index
  	   @frame = Frame.where(:store_id=>current_user.store_id)
  	   @len = Len.where(:store_id=>current_user.store_id)
       @sunglasse = Sunglasse.where(:store_id=>current_user.store_id)
  end

  def barcode_generate
  	  @frames = InventoryItem.where(:inventory_type => 'frame', :store_id => current_user.store_id, :barcode_status => false).all
      @lens = InventoryItem.where(:inventory_type => 'lense', :store_id => current_user.store_id, :barcode_status => false).all
      @sunglasse = InventoryItem.where(:inventory_type => 'sunglasse', :store_id => current_user.store_id, :barcode_status => false).all
      @barcode_for_html = '';
  	  # @barcode = Barby::Code128B.new('000000000000')
     #  @barcode_for_html = Barby::HtmlOutputter.new(@barcode)
      # bbcode
  end
  def get_frame_data
    
    inventory_item = InventoryItem.where(:id=> params[:frameid]).first
     if(params[:inverory_type] == "frame")
     @frame = inventory_item.frame
    elsif (params[:inverory_type] == "lense")
      @frame = inventory_item.len
    elsif (params[:inverory_type] == "sunglasse")
     @frame = inventory_item.sunglasse
   end
     @fid = @frame.id
     @fname = @frame.product.name
     @product_name = @frame.product_name
     @quantity = @frame.quantity
     @mrp = @frame.MRP     
     respond_to do |format|
       format.js { }
     end
  end
  def generate_barcode
      @pid = params[:BarCode][:inverory_id]
      @pname  = params[:BarCode][:product_name]
      @prate = params[:BarCode][:prate]
      @pqt = params[:BarCode][:quantity] 
      inventory_item = InventoryItem.where(:id=> @pid ).first
      @produc_name =
      @barcode = Barby::Code128B.new(@pid)
      @barcode_for_html = Barby::HtmlOutputter.new(@barcode)
      inventory_item.update_attribute(:barcode_status, true)

     respond_to do |format|  
            format.js
     end 
  end

  def bbcode
  	   if File.directory?("#{Rails.root}/public/barcodes") == false
	      system 'mkdir', '-p', "#{Rails.root}/public/barcodes"
	   end

	  [1,2,3,4,5,6].each do |barcode_number|
	    @barcode = Barby::Code128B.new(barcode_number)
	    @blob = Barby::PngOutputter.new(@barcode).to_png
	    File.open("#{Rails.root}/public/barcodes/#{barcode_number}.png", 'wb'){ |f|
	      f.write @blob
	    }

      end
   end
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/lens_helper.rb
module LensHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/inventory/_barcode_printable.html.erb
<div class="row">
 
</div>
                <!-- info row -->
<div class="row invoice-info">
 
  </div><!-- /.col -->



  <div class="col-md-6 invoice-col" style="margin-left: 50%">
    
  </div><!-- /.col -->
</div><!-- /.row -->

<div class="row">
   <%= render 'barcode_render' %>
	
</div>

<div class="row">

</div>

<div id="modal_terms">
	
</div>

app/views/inventory/_barcode_render.html.erb
 <divc id="bcodeDiv">
 <% if @barcode_for_html.present? %>
 <table style="margin: 20px;border: 1px solid black;">
    <tr><td></td><td></td><td style="padding-left: 80px;"><%= @pname %></td></tr>
    <tr><td style="padding-left: 10px;"><%= raw @barcode_for_html.to_html if @barcode_for_html.present?%></td><td></td><td style="padding-left: 80px;">MRP: <%= @prate %></td></tr>
    <tr><td style="text-align: center;"><%= @pid %> </td><td></td><td style="padding-left: 80px;">Net: <%= @prate %></td></tr>
  </table>
  <% end %>
  </div>
  <style type="text/css">

table.barby-barcode { border-spacing: 0; }
tr.barby-row {}
td.barby-cell { height: 50px; }
td.barby-cell.on { background: #000; }
</style>

app/views/inventory/barcode_generate.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          BarCode
          <small>Control panel</small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <!-- <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a> -->
            </li>
          </ol>
        </section>
        <section class="content">
          <div class="col-md-6">
            <div class="box">
              
              <!-- /.box-header -->
              <div class="box-body">
                <H1>BarCode Generator</H1>
                    <%= form_for :BarCode, url: "generate_barcode",:remote=>true do |f| %>
                      <div class="box-body">
                      <div class="form-group">
                      <label>Select Product </label>
                       <select id="slecte_inventory_type">
                        <option value="frame">Frame</option>
                        <option value="lense">Lens</option>
                        <option value="sunglasse">Sunglass</option>
                       </select>
                     
                      
                    </div>
                        <div class="form-group select_frame_name">
                          <label>Select Frame Name </label>
                          <%= f.select(:pid, options_for_select(@frames.map{ |c| [c.frame.product_name, c.id] }),{ include_blank: true },class: 'form-control frame_id') %>
                        </div>
                        <div class="form-group select_len_name">
                          <label>Select Lens Name </label>
                          <%= f.select(:pid, options_for_select(@lens.map{ |c| [c.len.product_name, c.id] }),{ include_blank: true },class: 'form-control frame_id') %>
                        </div>
                        <div class="form-group select_sunglasse_name">
                          <label>Select Sunglasse Name </label>
                          <%= f.select(:pid, options_for_select(@sunglasse.map{ |c| [c.sunglasse.product_name, c.id] }),{ include_blank: true },class: 'form-control frame_id') %>
                        </div>
                        <div class="form-group">
                          <label>Product Name</label>
                          <%= f.text_field :pname, autocomplete: "off", placeholder: "Product Name", class: "form-control", required: true, readonly: 'readonly'  %>
                          <%= f.hidden_field :inverory_id, value: '' %>
                          <%= f.hidden_field :product_name, value: '' %>
                        </div>
                        <div class="form-group">
                          <label>Rate </label>
                          <%= f.text_field :prate, autocomplete: "off", placeholder: "Enter Rate", readonly: 'readonly', class: "form-control"   %>
                        </div>
                        <div class="form-group">
                          <label>BarCodes Quantity</label>
                          <%= f.text_field :quantity, autocomplete: "off", placeholder: "Enter Barcode Quantity", class: "form-control",  readonly: 'readonly' %>
                        </div>
                      </div>
                      <!-- /.box-body -->
                      <div class="box-footer">
                        <%= f.submit "Generate", class: "btn btn-primary"%>
                        <div class="pull-right">
                         <button class="btn btn-primary" onclick="printDiv('print-barcode')">Print</button>
                        </div>
                      </div>



                      </div>
                      </div>
                      <% end  %>
              </div>
               <div id="print-barcode">
                <%= render 'barcode_render' %>
                </div>>
            </div>
            <!-- /.box -->
          </div>
          
        </section>
       
      </div>
    </div>
  </body>
  <script type="text/javascript">
    $( document ).ready(function() {
      $(".select_len_name").hide();
      $(".select_sunglasse_name").hide();
      $('.frame_id').on('change', function() {
        console.log(this)
         var fr_id = this.value ;
         var type  = $("#slecte_inventory_type").val();
         $("#BarCode_inverory_id").val(fr_id)
            $.ajax({
            url: "get_frame_data",
            method: "GET",  
            data: {frameid: fr_id, inverory_type: type },
            error: function (xhr, status, error) {
              console.error('AJAX Error: ' + status + error);
            },
            success: function (data) {
            }
          });
     });

      $("#slecte_inventory_type").on('change', function(){
         var type = this.value ;
         if(type == 'frame'){
          $(".select_frame_name").show();
          $(".select_len_name").hide();
          $(".select_sunglasse_name").hide();
         }
         else if(type == 'lense'){
          $(".select_frame_name").hide();
          $(".select_len_name").show();
          $(".select_sunglasse_name").hide();
         }
         else if(type == 'sunglasse'){
          $(".select_frame_name").hide();
          $(".select_len_name").hide();
          $(".select_sunglasse_name").show();
         }
        $('#BarCode_pname').val('');
        $('#BarCode_prate').val('');
        $('#BarCode_quantity').val('');
      });
});
  </script>

app/views/inventory/generate_barcode.js.erb
$("#bcodeDiv").html("<%= j render(partial: 'barcode_render') %>");

app/views/inventory/get_frame_data.js.erb
var fid = '<%= @fid %>';
var fname = '<%= @fname %>';
var qnt = '<%= @quantity %>';
var mrp = '<%= @mrp %>';
var product_name = '<%=@product_name%>'
$('#BarCode_pname').val(fname);
$('#BarCode_prate').val(mrp);
$('#BarCode_quantity').val(qnt);
 $("#BarCode_product_name").val(product_name)

app/views/inventory/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Inventory
          <small>Control panel</small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            
            </li>
          </ol>
        </section>
        <section class="content">
          <div class="col-md-6">
            <div class="box">
              <div class="box-header with-border">
                <h3 class="box-title">Frame (<%= @frame.count if @frame.present? %>)</h3>
                <%= link_to 'New Frame', new_frame_path , { class: "btn btn-primary newAddBtn"}%>
                <%= link_to 'Frames', frames_path , { class: "btn btn-primary newAddBtn"}%>

              </div>
              <div class="box-header with-border">
                <h3 class="box-title">Lens (<%= @len.count if @len.present? %>)</h3>
                <%= link_to 'New Lens', new_len_path , { class: "btn btn-primary newAddBtn"}%>
                 <%= link_to 'Lens', lens_path , { class: "btn btn-primary newAddBtn"}%>

              </div>

              <div class="box-header with-border">
                <h3 class="box-title">Sunglasse (<%= @sunglasse.count if @sunglasse.present? %>)</h3>
                <%= link_to 'New Sunglasse', new_sunglass_path , { class: "btn btn-primary newAddBtn"}%>
                <%= link_to 'Sunglasses', sunglasses_path , { class: "btn btn-primary newAddBtn"}%>

              </div>

              <div class="box-header with-border">
                <%= link_to 'Generate BarCode', inventory_barcode_generate_path , { class: "btn btn-primary newAddBtn"}%>

              </div>
              <!-- /.box-header -->
              <div class="box-body">
                
              </div>
            </div>
            <!-- /.box -->
          </div>
          <br>
        </section>
      </div>
    </div>
  </body>