config/routes.rb
Rails.application.routes.draw do
  
  
  
  resources :lens
  resources :sunglasses
  resources :frames
  resources :products
  resources :employees
  resources :stores
  resources :roles
  get 'home/index'
  devise_for :users

  root "home#index"

  get  'member/index'
  get  'member/create'
  post 'member/create_user'

  get 'inventory/index'
  get 'inventory/barcode_generate'
  post 'inventory/generate_barcode'
  get 'inventory/get_frame_data'

  get 'customer/index'
  get 'customer/create'
  get 'customer/edit'
  post 'customer/create_customer'

  get 'invoices/get_cust_data'
  get 'invoices/get_item_product'
  get 'invoices/edit'
  post 'invoices/generate_cust_invoice'

  get 'report/show_order_data'
  get 'report/index'
  get 'report/csv'
  get 'report/excel'

  get 'invoices/get_orderitemdata'


  resources :orders

  resources :invoices, except: [:destroy] do
    collection do
      match 'search' => 'invoices#search', via: [:get, :post], as: :search
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/frame.rb
class Frame < ApplicationRecord
  belongs_to :store
  belongs_to :product
  has_many :inventory_items
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
	belongs_to :frame, optional: true
	belongs_to :len, optional: true
	belongs_to :sunglasse, optional: true
	belongs_to :store
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  def self.delete_old
  	@old_invoices = Invoice.where('date < ?', 30.days.ago)
  	@old_invoices.delete_all
  end
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/len.rb
class Len < ApplicationRecord
  belongs_to :store
  belongs_to :product
  has_many :inventory_items
end

app/models/order.rb
require 'csv'

class Order < ApplicationRecord
	belongs_to :store
  has_many :order_details

	def self.to_csv
    attributes = %w{id store total_amt delivery_date }

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |order|
        csv << attributes.map{ |attr| order.send(attr) }
      end
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/store.rb
class Store < ApplicationRecord
	has_many :users
end

app/models/sunglasse.rb
class Sunglasse < ApplicationRecord
	belongs_to :store
	belongs_to :product
  	has_many :inventory_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  belongs_to :store
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to({:action => :index}, {:notice => 'Product was successfully created.'}) }
        # format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to({:action => :index}, {:notice => 'Product was successfully updated.'}) }
        # format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lens_helper.rb
module LensHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="box-body">
     <div class="form-group">

    <%= form.label :name %>
    <%= form.text_field :name , class: "form-control"%>

    <%= form.label :description %>
    <%= form.text_area :description , class: "form-control"%>
  </div>
  </div>

  <div class="box-footer">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Dashboard
          <small>Control panel</small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
            </li>
          </ol>
        </section>
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-header">
                <div class="box-header with-border">
                <h3 class="box-title">Edit Product</h3>
                </div>

                <%= render 'form', product: @product %>

                <%#= link_to 'Show', @role %> 
                <%#= link_to 'Back', roles_path %>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </body>

app/views/products/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Products
          <small></small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <!-- <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a> -->
            </li>
          </ol>
        </section>
        <section class="content">
          <div class="col-md-6">
            <div class="box">
              <div class="box-header with-border">
                <h3 class="box-title">Products (<%= @products.count %>)</h3>
                <%= link_to 'Add Product', new_product_path , { class: "btn btn-primary newAddBtn"}%>
              </div>
              <!-- /.box-header -->
              <div class="box-body">
                <table class="table table-bordered table-hover">
                  <tr>
                    <th>Name</th>
                    <th>Description</th>
                    
                    <th>
                      <i class="ion ion-edit"></i>
                    </th>
                    <th>
                      <i class="ion ion-trash-b"></i>
                    </th>
                  </tr>
                  <% @products.each do |product| %>
                  <tr>
                    <td><%= product.name %></td>
                    <td><%= product.description %></td>
                    <td><%= link_to "", edit_product_path(product), { class: "ion ion-edit"} %></td>
                    <td>
                      <%= link_to product, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="ion ion-trash-b"></i>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                </table>
              </div>
            </div>
            <!-- /.box -->
          </div>
          <br>
        </section>
      </div>
    </div>
  </body>

app/views/products/new.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Dashboard
          <small>Control panel</small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
            </li>
          </ol>
        </section>
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-header">
                <div class="box-header with-border">
                  <h3 class="box-title">New Product</h3>
                </div>

                <%= render 'form', product: @product %>

                <%#= link_to 'Back', roles_path %>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </body>


<%#= render 'form', product: @product %>
<%#= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>